import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { auth } from "@/auth";
import Logout from "@/components/Logout";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] });
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<html lang="en">
			<body className={`${poppins.className} bg-gray-900 antialiased`}>
				{session?.user?.email ? (
					<div>
						<p className="text-white">{session.user.email}</p>
						<Logout />
					</div>
				) : (
					<p className="text-white">currently no user logged in</p>
				)}

				{children}
				<Toaster />
			</body>
		</html>
	);
}
